# Generated by Django 5.2 on 2025-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Store Staff'), ('clerk', 'Inventory Clerk'), ('sales', 'Sales Staff')], default='staff', max_length=20),
        ),
    ]
