# Generated by Django 5.2 on 2025-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_transfers',
            field=models.BooleanField(default=False),
        ),
    ]
