# Generated by Django 5.2 on 2025-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_view_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_adjust_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_transfer_stock',
            field=models.BooleanField(default=False),
        ),
    ]
