# Generated by Django 5.2 on 2025-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_purchaseorderitem_expected_sales_price'),
        ('users', '0005_user_can_adjust_stock_user_can_transfer_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, to='inventory.store'),
        ),
    ]
