# Generated by Django 5.2 on 2025-05-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_store_user_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_approve_transfers',
            field=models.BooleanField(default=False),
        ),
    ]
