services:
  - type: web
    name: inventrax
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: inventrax-db
          property: connectionString
    disks:                           # ✅ FIXED THIS KEY
      - name: media
        mountPath: /media
        sizeGB: 1                    # ✅ Make sure the disk is mounted at /media

databases:
  - name: inventrax-db
