# Generated by Django 5.2 on 2025-04-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_remove_supplier_contact_info_store_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False},
        ),
    ]
