# Generated by Django 5.2 on 2025-04-15 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='transfer_date',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
