# Generated by Django 5.2 on 2025-04-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
            preserve_default=False,
        ),
    ]
