# Generated by Django 5.2 on 2025-04-30 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_account_type'),
        ('inventory', '0021_sale_sale_type_alter_sale_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sales', to='accounting.transaction'),
        ),
    ]
