# Generated by Django 5.2 on 2025-04-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_sale_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bank',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
