# Generated by Django 5.2 on 2025-04-30 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_account_type'),
        ('inventory', '0023_remove_sale_bank_delete_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_record', to='accounting.transaction'),
        ),
    ]
