# Generated by Django 5.2 on 2025-05-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_saleitem_cost_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'store')},
        ),
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
    ]
