# Generated by Django 5.2 on 2025-05-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_stock_unique_together_stock_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
