# Generated by Django 5.2 on 2025-05-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_transaction_store'),
        ('inventory', '0028_remove_purchase_supplier_name_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction'),
        ),
    ]
