# Generated by Django 5.2 on 2025-05-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_transaction_store'),
        ('inventory', '0029_purchase_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cogs_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_sale', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='sale',
            name='revenue_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_sale', to='accounting.transaction'),
        ),
    ]
