# Generated by Django 5.2 on 2025-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_sale_cogs_transaction_sale_revenue_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
