# Generated by Django 5.2 on 2025-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_stock_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
