# Generated by Django 5.2 on 2025-05-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_stocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('adjustment', 'Stock Adjustment'), ('transfer', 'Stock Transfer'), ('create_user', 'User Created'), ('delete_user', 'User Deleted'), ('expense', 'Expense Entry')], max_length=50),
        ),
    ]
