# Generated by Django 5.2 on 2025-05-19 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auditlog_store_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.store'),
        ),
    ]
