# Generated by Django 5.2 on 2025-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_purchaseorder_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expected_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
