# Generated by Django 5.2 on 2025-05-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_purchaseorderitem_expected_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
