# Generated by Django 5.2 on 2025-05-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_supplierpayment_transaction_and_more'),
        ('inventory', '0038_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Reference to the initial inventory transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction'),
        ),
    ]
