# Generated by Django 5.2 on 2025-05-25 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_notification_user'),
        ('inventory', '0041_stocktransfer_created_by_alter_stocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_transaction',
            field=models.ForeignKey(blank=True, help_text='Linked transaction for accounting purposes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to='accounting.transaction'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
