# Generated by Django 5.2 on 2025-05-31 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_remove_customer_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='converted_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_source', to='inventory.sale'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_to_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
