# Generated by Django 5.2 on 2025-05-31 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_quotation_converted_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='converted_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_quotation', to='inventory.sale'),
        ),
    ]
