# Generated by Django 5.2 on 2025-04-26 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(
                to='accounting.account',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='incoming_transactions',
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(
                to='accounting.account',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outgoing_transactions',
                null=True,
                blank=True
            ),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('asset', 'Asset'),
                    ('liability', 'Liability'),
                    ('equity', 'Equity'),
                    ('revenue', 'Revenue'),
                    ('expense', 'Expense')
                ]
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
