# Generated by Django 5.2 on 2025-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense'), ('bank', 'Bank'), ('undeposited', 'Undeposited Funds')], max_length=50),
        ),
    ]
