# Generated by Django 5.2 on 2025-05-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_account_slug_alter_account_name_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
