# Generated by Django 5.2 on 2025-05-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_account_slug'),
        ('inventory', '0026_alter_stock_unique_together_stock_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, limit_choices_to={'type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction')),
            ],
        ),
    ]
