# Generated by Django 5.2 on 2025-05-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_account_type_alter_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
