# Generated by Django 5.2 on 2025-05-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_expenseentry_options_expenseentry_recorded_by_and_more'),
        ('inventory', '0035_purchaseorderitem_expected_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='inventory.store'),
        ),
    ]
