# Generated by Django 5.2 on 2025-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_transaction_destination_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination_store',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_store',
        ),
    ]
