# Generated by Django 5.2 on 2025-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
