# Generated by Django 5.2 on 2025-05-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_notification_user'),
        ('accounting', '0026_populate_account_slugs'),
    ]

    operations = [
    ]
