# Generated by Django 5.2 on 2025-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_merge_20250529_1919'),
        ('inventory', '0049_alter_quotation_converted_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='inventory.purchaseorder'),
        ),
    ]
